project:
  type: website
  output-dir: docs

website:
  favicon: images/favicon-32x32.png
  title: "portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Portfolio
      - href: about.qmd
        text: About Me
      - href: dlensembling.qmd
        text: NN Ensembling

format:
  html:

    theme: solar
    css: styles.css
    toc: true



