project:
  type: website
  output-dir: docs

website:
  google-analytics: "G-ZVECF4ZDF3"
  favicon: images/favicon-32x32.png
  title: "portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Portfolio
      - href: about.qmd
        text: About Me
      #- href: dlensembling.qmd
      #  text: NN Ensembling
  sidebar:
      background: "#D9E3E4"
      logo: "images/cdicon.png"
      pinned: true
      align: center
      tools:
        - icon: github
          href: https://github.com/sta210-s22
          text: "GitHub organization"

      style: "docked"
      search: true
      collapse-level: 1
      contents:
        - section: "Course information"
          contents:
            - href: projects/dl_example.qmd
              text: Overview
          
format:
  html:

    theme: solar
    css: styles.css
    toc: true



