project:
  type: website
  output-dir: docs

website:
  google-analytics: "G-ZVECF4ZDF3"
  favicon: images/favicon-32x32.png
  title: "portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Portfolio
      - href: about.qmd
        text: About Me
      #- href: dlensembling.qmd
      #  text: NN Ensembling
  sidebar:
      #background: "#D9E3E4"
      logo: "images/self.png"
      pinned: true
      align: center
      tools:
        - icon: github
          href: https://github.com/corwindark
          text: "Check out my Github!"
        - icon: linkedin
          href: https://linkedin.com/in/corwindark
          text: "Check out my Linkedin!"
        - icon: envelope
          url: mailto:corwindark@gmail.com

      style: "floating"
      search: true
      collapse-level: 1
      contents:
        - section: "Course information"
          contents:
            - href: projects/dl_example.qmd
              text: Overview
          
format:
  html:

    theme: solar
    css: styles.css
    toc: true



