project:
  type: website

website:
  title: "portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: projects/dlensembling/dlensembling.qmd
        text: Metalearning Neural Network
      - about.qmd

format:
  html:
    theme: solar
    css: styles.css
    toc: true



